import dotenv from 'dotenv'
// const dotenv = require('dotenv')
dotenv.config()
export const env = {
    MONGODB_URI: process.env.MONGODB_URI,
    DATABASE_NAME: process.env.DATABASE_NAME,
    APP_PORT: process.env.APP_PORT,
    AUTHOR:process.env.AUTHOR, 
    APP_HOST: process.env.APP_HOST,
    JWT_SECRET: process.env.JWT_SECRET,
    EMAIL_HOST:process.env.EMAIL_HOST, 
    EMAIL_PORT: process.env.EMAIL_PORT,
    EMAIL_USER:process.env.EMAIL_USER,
    EMAIL_PASS:process.env.EMAIL_PASS,
    APP_URL:process.env.BUILD_MODE === 'production' ? process.env.PROD_URL : process.env.DEV_URL,
    APP_FRONT_URL: process.env.BUILD_MODE === 'production' ? process.env.PROD_FRONT_URL : process.env.DEV_FRONT_URL,
    RESEND_APIKEY:process.env.RESEND_APIKEY, 
    ACCESS_TOKEN_SECRET_KEY :process.env.ACCESS_TOKEN_SECRET_KEY, 
    REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET, 
    DEV_FRONT_URL: process.env.DEV_FRONT_URL, 
    PROD_FRONT_URL: process.env.PROD_FRONT_URL,
    DEV_BACK_URL: process.env.DEV_BACK_URL, 
    PROD_BACK_URL: process.env.PROD_BACK_URL, 
    SMTP_HOST:process.env.SMTP_HOST, 
    SMTP_PORT: process.env.SMTP_PORT, 
    SMTP_USER:process.env.SMTP_USER, 
    SMTP_PASS:process.env.SMTP_PASS, 
    EMAIL_FROM_NAME:process.env.EMAIL_FROM_NAME, 
    COMPANY_NAME: process.env.COMPANY_NAME, 
    CONTACT_EMAIL:process.env.CONTACT_EMAIL, 
    SMTP_FROM:process.env.SMTP_FROM
}